#version 450

layout (local_size_x = 64, local_size_y = 64) in;

layout (set = 0, binding = 0, r32f) uniform readonly image2D u_inDepthText;
layout (set = 0, binding = 1, r16_snorm) uniform writeonly image2D u_outDepthTex;

void main() {
    float inDepth = imageLoad(u_inDepthText, ivec2(gl_GlobalInvocationID.xy)).r;

    imageStore(u_outDepthTex, ivec2(gl_GlobalInvocationID.xy), vec4(inDepth, 0.0, 0.0, 0.0));
}
